### ISSUE TITLE
Missing default user after run docker-compose

### ISSUE THREAD

**Issue by vincestone** [UniBee-Billing/unibee#12]
## Description

After following the official Docker installation process, no default user is created. The system appears to lack any user data.

## How to reproduce
 
1. Follow the official UniBee documentation for installing via Docker (https://docs.unibee.dev/documentation/install/how-to-install).
```
# Get the code
git clone https://github.com/UniBee-Billing/unibee_deploy.git

# Go to folder
cd unibee_deploy

# Deploy
docker-compose up

# Start Admin Portal
Open Link: http://localhost
Buildin Merchant Account: accounts.unibee@unibee.dev
Buildin Merchant Pass: changeme
```

2. Open the admin portal on http://localhost
3. Try to login with accounts.unibee@unibee.dev/changeme

## Result

I got the following error: Email Not Found
The user_account table has no entries.

## Expectations

There should be a default user created when the containers start.

## Environment

- UniBee version: 1.1.0 (images: mysql:8.0.13, unibee/api:v1.1.0, admin-portal:v1.1.0)
- Operating system: Windows 10 with docker desktop

**Comment by mistricky** [comment]
Hi @vincestone, thx for using UniBee, The [documentation](https://docs.unibee.dev/documentation/install/how-to-install) is outdated, and we no longer provide built-in accounts, we will update the documentation as soon.

**Comment by olystelecom** [comment]
Hi Team!

Any chance that we could get a pre-configured database for this please?
The current database is not loaded with any data at the moment. Just empty tables which makes it even harder to even create an admin account as we do not know which values are expected by the application it self. 

I created a merchant under the following tables but it opens me up to an empty page.

merchant
merchant_member
merchant_roles > even this table is empty 

Anything to get this application up and running would be appriciated.

**Comment by UniBeeYvonne** [comment]
Hi! @olystelecom  Please contact help@unibee.dev and we will send you a sandbox account.
